jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install jlpm
      run: |
        python -m pip install --upgrade pip
        pip install jupyterlab
    - name: Install dependencies
      run: |
        jlpm install
    - name: Build project
      run: |
        jlpm build
    - name: Authenticate to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_API_TOKEN }}" > ~/.npmrc
    - name: Publish
      run: npm publish --access=public